### ISSUE TITLE
FSM CLI support list current connectors

### ISSUE THREAD

**Issue by addozhang** [flomesh-io/fsm#189]
**Please describe the Improvement and/or Feature Request**

FSM CLI should support listing current connectors, like:

```shell
fsm connector list
```

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Gateway                     [ ]
- Connector                    []
- Sidecar Control Plane        [ ]
- CLI Tool                   [x]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by cybwan** [comment]
Add connector crd, and support kubectl get.
