### ISSUE TITLE
Support Ingress Access from control plan

### ISSUE THREAD

**Issue by rockburning** [flomesh-io/fsm#196]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

When using karmda there are multi ingress support with its own mcs api;  but when using ingress-pipy, cannot access using the same usage; I was wondering if there any plan to enhance this feature

**Comment by reaver-flomesh** [comment]
will you pls give an example of what you're talking about?

**Comment by reaver-flomesh** [comment]
no further input, will be closed.
