### ISSUE TITLE
Request to revert OSS licenses of flomesh modules

### ISSUE THREAD

**Issue by UltraInstinct14** [flomesh-io/fsm#317]
I am one of the maintainers of [loxilb](https://github.com/loxilb-io/loxilb). It has come to our notice that Flomesh repo https://github.com/flomesh-io/flb/tree/main/ebpf has changed the original copyright of [loxilb-ebpf](https://github.com/loxilb-io/loxilb-ebpf) modules.

If it is due to some mistake, we request to revert the original license. If not, we request to take down the repository at the earliest. @cybwan  @addozhang  @naqvis  @keveinliu @reaver-flomesh  @wanpf

**Comment by keveinliu** [comment]
We've closed `flb` as per your request.
And this repo is not related to `flb` or `loxilib`, will close this issue as well.
